"""add version to lists

Revision ID: 45b34e878e15
Revises: b514facaa928
Create Date: 2026-08-29 11:27:54.340552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45b34e878e15'
down_revision: Union[str, Sequence[str], None] = 'b514facaa928'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lists', sa.Column('version', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lists', 'version')
    # ### end Alembic commands ###
